CREATE TABLE IF NOT EXISTS `Variables` (
	`TypeKind`	INTEGER NOT NULL,
	`TypeIdx`	INTEGER NOT NULL,
	`Name`	INTEGER NOT NULL,
	`SourceLocationIdx`	INTEGER,
	`StorageLocationIdx`	INTEGER,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT,
	FOREIGN KEY(`Name`) REFERENCES `Identifiers`(`Idx`)
);

CREATE TABLE IF NOT EXISTS `Types` (
	`Kind`	INTEGER NOT NULL,
	`ElementIdx`	INTEGER,
	`Name`	TEXT,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS `Structs` (
	`Name`	INTEGER,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE IF NOT EXISTS `Strings` (
	`String`	TEXT,
	`Hash`	INTEGER NOT NULL,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE IF NOT EXISTS `Locations` (
	`FullPath`	TEXT,
	`StartLine`	INTEGER,
	`StartCol`	INTEGER,
	`LineSpan`	INTEGER,
	`EndCol`	INTEGER,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE IF NOT EXISTS `Identifiers` (
	`Name`	TEXT,
	`Hash`	INTEGER NOT NULL,
	`Idx`	INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE IF NOT EXISTS `Files` (
	`FileName`	TEXT NOT NULL,
	`FullPath`	TEXT NOT NULL,
	`FileHash`	INTEGER NOT NULL,
	`LexerHash`	INTEGER NOT NULL,
	`Content`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Fields` (
	`StructIdx`	INTEGER NOT NULL,
	`FieldIdx`	INTEGER NOT NULL,
	`Identifier`	INTEGER,
	`TypeIdx`	INTEGER,
	`Offset`	INTEGER,
	FOREIGN KEY(`Identifier`) REFERENCES `Identifiers`(`Idx`),
	FOREIGN KEY(`TypeIdx`) REFERENCES `Types`(`Idx`),
	PRIMARY KEY(`StructIdx`)
);
COMMIT;
